const quizData1 = [
    {
        question: "Question 1: \nIf a student is sitting in their chair and the leg of the chair breaks the student will __________ toward the floor because the gravity is a greater force.",
        a: "Accelerate",
        b: "Force",
        c: "Balance",
        d: "Speed",
        correct: "a",
    },
    {
        question: "Question 2: \nA force that resists the movement of one surface against another. ",
        a: "Centripetal",
        b: "Inertia",
        c: "Friction",
        d: "Kinetic",
        correct: "c",
    },
    {
        question: "Question 3: \nI have a large yoyo that must move to open my cash register drawer, therefore I use a large baseball to move the yoyo. ",
        a: "Newton's First Law of Motion",
        b: "Newton's Second Law of Motion",
        c: "Newton's Third Law of Motion",
        d: "Newton's Fourth Law of Motion",
        correct: "b",
    },
    {
        question: "Question 4: \nThe amount of force exerted on an object due to gravity. ",
        a: "Weight",
        b: "Force",
        c: "Momentum",
        d: "Inertia",
        correct: "a",
    },
    {
        question: "Question 5: \nThe amount of matter in an object. ",
        a: "Velocity",
        b: "Inertia",
        c: "Mass",
        d: "Weight",
        correct: "c",
    },
    {
        question: "Question 6: \nThe energy of motion or the energy an object has as a result of its motion.",
        a: "Kinetic",
        b: "Momentum",
        c: "Speed",
        d: "Acceleration",
        correct: "a",
    },
    {
        question: "Question 7: \nThe Wheeler Dealer bumper cars is a perfect example of every action having a sepearate but equal reaction.  This is an example of which law of motion? ",
        a: "Newton's First Law of Motion",
        b: "Newton's Second Law of Motion",
        c: "Newton's Third Law of Motion",
        d: "Newton's Fourth Law of Motion",
        correct: "c",
    },
    {
        question: "Question 8: \nA unit of measurement for force. ",
        a: "Mass",
        b: "Gram",
        c: "psi",
        d: "Newton",
        correct: "d",
    },
    {
        question: "Question 9: \nThis describes an object's velocity, or speed with a direction. ",
        a: "State of rest",
        b: "State of balance",
        c: "State of California",
        d: "State of motion",
        correct: "d",
    },
    {
        question: "Question 10: \nThe type of foce that keeps objects moving in a circle or arc. ",
        a: "Gravity",
        b: "Friction",
        c: "Momentum",
        d: "Centripetal",
        correct: "d",
    },
];

const quizData2 = [
    {
        question: "Question 1: \nA location to which you can compare other locations is called",
        a: "Reference point",
        b: "Motion",
        c: "Location",
        d: "Position",
        correct: "a",
    },
    {
        question: "Question 2: \nThe change of position over time is called",
        a: "Position",
        b: "Motion",
        c: "Speed",
        d: "Location",
        correct: "b",
    },
    {
        question: "Question 3: \nThe measure of how quickly something moves or the distance it moves in a given amount of time is called",
        a: "Motion",
        b: "Position",
        c: "Speed",
        d: "Location",
        correct: "c",
    },
    {
        question: "Question 4: \nThe unit speed is measured in is",
        a: "m/s",
        b: "ft/min",
        c: "m/hr",
        d: "m/s^2",
        correct: "a",
    },
    {
        question: "Question 5: \nSpeed is equal to the distance divided by",
        a: "Position",
        b: "Time",
        c: "Height",
        d: "Mass",
        correct: "b",
    },
    {
        question: "Question 6: \nsoccer ball is kicked from 40 meters out. It takes 5 seconds to reach the goal. What speed was the ball traveling? \nd= 40 m \nt= 5 s",
        a: "6 m/s ",
        b: "7 m/s",
        c: "8 m/s",
        d: "9 m/s",
        correct: "c",
    },
    {
        question: "Question 7: \nIn a distance time graph, the steeper the line the...",
        a: "Greater the speed",
        b: "Slower the speed",
        c: "Speed has reached zero",
        d: "Speed has not changed",
        correct: "a",
    },
    {
        question: "Question 8: \nA(n) __________ is a push or pull.",
        a: "Newton",
        b: "Acceleration",
        c: "Force",
        d: "Momentum",
        correct: "c",
    },
    {
        question: "Question 9: \nWhich law best describes- A satellite orbiting the earth.",
        a: "Law of Inertia",
        b: "Law of Mass and Acceleration",
        c: "Law of Action Reaction",
        d: "Law of Gravity",
        correct: "a",
    },
    {
        question: "Question 10: \nWhat pulls a ball back to earth?",
        a: "Gravity",
        b: "Gas",
        c: "Friction",
        d: "Molecules",
        correct: "a",
    },
];

const quizData3 = [
    {
        question: "Question 1: \nWhich best explains why we are able to accelerate forward when starting to run?",
        a: "As one leg moves backward, it provides an equal and opposite force for the other foot to move forward.",
        b: "No acceleration takes place. Runners are always at a fixed velocity.",
        c: "The striking foot pushes backward against the ground. The friction with the ground provides an equal and opposite force forward.",
        d: "The runner's upper body quickly leans forward, causing the entire body to begin accelerating forward",
        correct: "c",
    },
    {
        question: "Question 2: \nSPEED and a DIRECTION is called",
        a: "Speed",
        b: "Velocity",
        c: "Direction",
        d: "Force",
        correct: "b",
    },
    {
        question: "Question 3: \nVelocity is speed in a given...",
        a: "Direction ",
        b: "Acceleration ",
        c: "Force ",
        d: "Mass",
        correct: "a",
    },
    {
        question: "Question 4: \nYou and your dad are moving the couch from one side of the room to another. Your dad pushes with a force of 300 N to the right and you push with a force of 300 N right. What is the net force on the couch?",
        a: "0 N right",
        b: "0 N left",
        c: "600 N right",
        d: "600 N left",
        correct: "c",
    },
    {
        question: "Question 5: \nRockets are launched into space using jet propulsion where exhaust accelerates out from the rocket and the rocket accelerates in an opposite direction.",
        a: "The Law of Inertia",
        b: "The Law of Acceleration",
        c: "The Law of Conservation of Momentum",
        d: "The Law of Gravity",
        correct: "c",
    },
    {
        question: "Question 6: \nA person not paying attention while skateboarding hits a rock. The skateboard stops...they don't.",
        a: "The Law of Inertia",
        b: "The Law of Acceleration",
        c: "The Law of Conservation of Momentum",
        d: "The Law of Gravity",
        correct: "a",
    },
    {
        question: "Question 7: \nForce exerted between the surfaces of two objects.",
        a: "Friction",
        b: "Inertia",
        c: "Force ",
        d: "Gravity",
        correct: "a",
    },
    {
        question: "Question 8: \nObjects tendency to resist change",
        a: "Friction",
        b: "Inertia",
        c: "Force",
        d: "Gravity",
        correct: "b",
    },
    {
        question: "Question 9: \nA measure of how much matter an object has is--",
        a: "Weight",
        b: "Volume",
        c: "Gravity ",
        d: "Mass",
        correct: "d",
    },
    {
        question: "Question 10: \nThe weight of an object _________ as it moves away from the center of Earth.",
        a: "Increases",
        b: "Stays the same",
        c: "Triples",
        d: "Decreases",
        correct: "d",
    },
];
